import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/global/Provider/Providers";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-arp="" suppressHydrationWarning>
      <body className={` font antialiased`} cz-shortcut-listen="true">
        <Providers>
          <ThemeProvider defaultTheme="dark">{children}</ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
